language: node_js
services:
- rabbitmq
node_js:
- 'stable'
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
