language: node_js
services:
- rabbitmq
node_js:
- stable
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- npm run build
before_script:
- mosquitto -c spec/utils/mosquitto.conf -d
- './node_modules/.bin/simple-server . &'
script:
- npm test
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: Hvnuk4NZNa6Jen0g5cQqt2iJVLHeFcGTO07powcHc3PiYsCSOaFHPaV6H5oFd8iiD13lsjtJSxM2102kp8sUSI1XhE0mo0fKERONizB9pIpO6I3QMp/kKFE/FS/f2dbfyAgRXvwSKoYC18l1VGV+cax2HMBZs/0WnYfe1gIB/JwR3vVxUtOi9qK0Jhydgujv5YsW0sJgnhYupB6UB0i6ww0jPL6BTB1T8W3dIc83BZXMXHPMmsI+uNQIxss/z3feOv+dSxyjE8oXGScuUc0qzRtm9HEG0uO5Neq/MXQoW/O0mfG4AIZwx5Q3z4BP5R04oYweHiLt+zUD9DUziR6nORBdn0dcEfNkgIeGFtCEnxt5m+HwFZd/wz8J1m3CddDaGRs6XqSOmLumLKrDjifxCuhzoBwv7iTNKq7Gczo3ppm9eC4mlrC1fnpQUglzC7NhP9AO5seQkuaF6ihsxHnsoa3I11H+p0++Bec73cV6hXbhnFieVcQO3RaDf1oPWjeL6g94PisjVscyAlY854ujVqEvBF3ayLfbsWEEugbXpzZ6ir1MWMb3YmkFCfW1onWh418Za5AifKyPrFKJRLojgJ5SKI2IFtfqR0L/K/1KO9GJk03uGMhVlh3Iq+sQxfcjo3GKKaOGP8+uJ4r/Zqb63OeyISZCZo2ctjeLlGdBUgQ=
  on:
    tags: true
    repo: msgflo/msgflo-browser
